package com.example.user.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Document(collection = "users")
public class UserId {
    @Id
    private String id; // ObjectId generated by MongoDB
    private String password;
    private String nickname;
    private String avatar;
    private int coins;
    private List<CoinRecord> coinsRecord;
    private List<String> followed;
    private List<String> follower;
    private List<String> blacklist;
    private List<String> questionsAsk;
    private List<String> questionsAsw;
    private List<String> questionsCollect;
    private String ipaddress;

    
}
