/*
 * aorb
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InlineObject1 struct {

	// 用户名/用户ID
	Id string `json:"id"`

	// 密码的md5摘要
	Pwd string `json:"pwd"`
}
