/*
 * aorb
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InlineObject struct {

	// 用户ID
	UserId string `json:"user_id"`

	// 拉黑的用户ID
	BlackId string `json:"black_id"`
}
