/*
 * aorb
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Question struct {

	// 问题ID
	Id string `json:"id"`

	// 问题类型：公开/私密/匿名
	Type string `json:"type"`

	// 问题题目
	Title string `json:"title"`

	// 问题选项
	Options []string `json:"options"`

	// 发起时间
	Time string `json:"time"`

	// 发布频道
	Channel string `json:"channel"`

	// 发起人
	Sponsor string `json:"sponsor"`

	// 邀请好友ID
	InviteIds []string `json:"invite_ids,omitempty"`

	// 投票者和他的建议
	Voters []string `json:"voters"`

	// 评论区
	Comments []QuestionComments `json:"comments"`

	// 推荐费用
	Fee *int32 `json:"fee,omitempty"`
}
