/*
 * aorb
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type QuestionComments struct {

	// 立场
	Choose string `json:"choose"`

	// 用户名
	Userid string `json:"userid"`

	// 建议
	Advise string `json:"advise"`
}
