/*
 * aorb
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InlineObject2 struct {

	UserId string `json:"user_id"`

	FollowId string `json:"follow_id"`
}
