openapi: 3.0.1
info:
  title: aorb
  version: 1.0.0
servers:
- url: /
tags:
- name: 用户信息
- name: 投票
- name: 用户管理
paths:
  /v1/polls:
    get:
      deprecated: false
      parameters:
      - description: 用于查询该用户特定喜好的领域，并推荐问题
        explode: true
        in: query
        name: user_id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 获取所有的投票
      tags:
      - 投票
      x-apifox-folder: 投票
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166237045-run
    post:
      deprecated: false
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 创建新的投票
      tags:
      - 投票
      x-apifox-folder: 投票
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166236919-run
  /v1/user/blacklist:
    post:
      deprecated: false
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                user_id:
                  description: 用户ID
                  title: 用户ID
                  type: string
                black_id:
                  description: 拉黑的用户ID
                  title: 拉黑的用户ID
                  type: string
              required:
              - black_id
              - user_id
              type: object
              x-apifox-orders:
              - user_id
              - black_id
              x-apifox-ignore-properties: []
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 拉黑用户
      tags:
      - 用户信息
      x-apifox-folder: 用户信息
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166245490-run
  /v1/user/login:
    get:
      deprecated: false
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            schema:
              properties:
                id:
                  description: 用户名/用户ID
                  title: 用户名/用户ID
                  type: string
                pwd:
                  description: 密码的md5摘要
                  title: 密码的md5摘要
                  type: string
              required:
              - id
              - pwd
              type: object
              x-apifox-orders:
              - id
              - pwd
              x-apifox-ignore-properties: []
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 登录
      tags:
      - 用户管理
      x-apifox-folder: 用户管理
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166245927-run
  /v1/polls/question:
    get:
      deprecated: false
      parameters:
      - description: 问题的ID
        explode: true
        in: query
        name: question_id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 获取单个投票详情
      tags:
      - 投票
      x-apifox-folder: 投票
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166336555-run
    post:
      deprecated: false
      parameters:
      - explode: true
        in: query
        name: question_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 为问题投票
      tags:
      - 投票
      x-apifox-folder: 投票
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166343778-run
  /v1/user/follower:
    post:
      deprecated: false
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                follow_id:
                  type: string
              required:
              - follow_id
              - user_id
              type: object
              x-apifox-orders:
              - user_id
              - follow_id
              x-apifox-ignore-properties: []
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 关注用户/取关用户
      tags:
      - 用户信息
      x-apifox-folder: 用户信息
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166342198-run
  /v1/user/info:
    get:
      deprecated: false
      parameters:
      - explode: true
        in: query
        name: user_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: 成功
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: 记录不存在
      summary: 获取用户基本信息
      tags:
      - 用户信息
      x-apifox-folder: 用户信息
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166347974-run
  /v1/bignosecat:
    get:
      deprecated: false
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      summary: 开发者信息
      tags: []
      x-apifox-folder: ""
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/4351857/apis/api-166352576-run
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
  schemas:
    Question:
      example:
        sponsor: sponsor
        comments:
        - advise: advise
          choose: choose
          userid: userid
        - advise: advise
          choose: choose
          userid: userid
        voters:
        - voters
        - voters
        fee: 0
        options:
        - options
        - options
        channel: channel
        id: id
        time: time
        type: public
        title: title
        invite_ids:
        - invite_ids
        - invite_ids
      properties:
        id:
          description: 问题ID
          type: string
        type:
          description: 问题类型：公开/私密/匿名
          enum:
          - public
          - secret
          - anonymous
          type: string
          x-apifox:
            enumDescriptions:
              public: 公开投票
              secret: 私密投票
              anonymous: 匿名投票
        title:
          description: 问题题目
          type: string
        options:
          description: 问题选项
          items:
            type: string
          type: array
        time:
          description: 发起时间
          type: string
        channel:
          description: 发布频道
          type: string
        sponsor:
          description: 发起人
          type: string
        invite_ids:
          description: 邀请好友ID
          items:
            type: string
          type: array
        voters:
          description: 投票者和他的建议
          items:
            type: string
          type: array
        comments:
          description: 评论区
          items:
            $ref: '#/components/schemas/Question_comments'
          type: array
        fee:
          description: 推荐费用
          minimum: 0
          nullable: true
          type: integer
      required:
      - channel
      - comments
      - id
      - options
      - sponsor
      - time
      - title
      - type
      - voters
      type: object
      x-apifox-orders:
      - id
      - type
      - title
      - options
      - time
      - channel
      - sponsor
      - invite_ids
      - voters
      - comments
      - fee
      x-apifox-ignore-properties: []
      x-apifox-folder: ""
    User:
      properties:
        id:
          description: 用户ID
          type: string
        nickname:
          description: 用户昵称
          type: string
        avatar:
          description: 用户头像
          type: string
        coins:
          description: 用户的金币数
          minimum: 0
          type: number
        coins_record:
          description: 用户金币流水记录
          items:
            type: string
          nullable: true
          type: array
        followed:
          description: 关注者
          items:
            type: string
          type: array
        follower:
          description: 被关注者
          items:
            type: string
          type: array
        blacklist:
          description: 屏蔽好友
          items:
            type: string
          type: array
        questions_ask:
          description: 发起过的问题
          items:
            type: string
          type: array
        questions_asw:
          description: 回答过的问题
          items:
            type: string
          type: array
        channels:
          description: 关注的频道
          items:
            type: string
          type: array
      required:
      - avatar
      - blacklist
      - channels
      - coins
      - coins_record
      - followed
      - follower
      - id
      - nickname
      - questions_ask
      - questions_asw
      type: object
      x-apifox-orders:
      - id
      - nickname
      - avatar
      - coins
      - coins_record
      - followed
      - follower
      - blacklist
      - questions_ask
      - questions_asw
      - channels
      x-apifox-ignore-properties: []
      x-apifox-folder: ""
    inline_object:
      properties:
        user_id:
          description: 用户ID
          title: 用户ID
          type: string
        black_id:
          description: 拉黑的用户ID
          title: 拉黑的用户ID
          type: string
      required:
      - black_id
      - user_id
      type: object
      x-apifox-orders:
      - user_id
      - black_id
      x-apifox-ignore-properties: []
    inline_object_1:
      properties:
        id:
          description: 用户名/用户ID
          title: 用户名/用户ID
          type: string
        pwd:
          description: 密码的md5摘要
          title: 密码的md5摘要
          type: string
      required:
      - id
      - pwd
      type: object
      x-apifox-orders:
      - id
      - pwd
      x-apifox-ignore-properties: []
    inline_object_2:
      properties:
        user_id:
          type: string
        follow_id:
          type: string
      required:
      - follow_id
      - user_id
      type: object
      x-apifox-orders:
      - user_id
      - follow_id
      x-apifox-ignore-properties: []
    inline_response_200:
      example:
        questions_ask:
        - questions_ask
        - questions_ask
        follower:
        - follower
        - follower
        channels:
        - channels
        - channels
        coins: 0.08008281904610115
        questions_asw:
        - questions_asw
        - questions_asw
        nickname: nickname
        blacklist:
        - blacklist
        - blacklist
        id: id
        avatar: avatar
        followed:
        - followed
        - followed
        coins_record:
        - coins_record
        - coins_record
      properties:
        id:
          description: 用户ID
          type: string
        nickname:
          description: 用户昵称
          type: string
        avatar:
          description: 用户头像
          type: string
        coins:
          description: 用户的金币数
          minimum: 0
          type: number
        coins_record:
          description: 用户金币流水记录
          items:
            type: string
          nullable: true
          type: array
        followed:
          description: 关注者
          items:
            type: string
          type: array
        follower:
          description: 被关注者
          items:
            type: string
          type: array
        blacklist:
          description: 屏蔽好友
          items:
            type: string
          type: array
        questions_ask:
          description: 发起过的问题
          items:
            type: string
          type: array
        questions_asw:
          description: 回答过的问题
          items:
            type: string
          type: array
        channels:
          description: 关注的频道
          items:
            type: string
          type: array
      required:
      - avatar
      - blacklist
      - channels
      - coins
      - coins_record
      - followed
      - follower
      - id
      - nickname
      - questions_ask
      - questions_asw
    inline_response_404:
      properties:
        err:
          type: string
      required:
      - err
    Question_comments:
      example:
        advise: advise
        choose: choose
        userid: userid
      properties:
        choose:
          description: 立场
          type: string
        userid:
          description: 用户名
          type: string
        advise:
          description: 建议
          type: string
      required:
      - advise
      - choose
      - userid
