import 'package:flutter/material.dart';
import 'screens/home_recommended.dart';

void main() {
  runApp(const Aorb());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Aorb extends StatelessWidget {
  const Aorb({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Aorb: Decision Helper',
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.white,
      ),
      home: HomeRecommended(),
    );
  }
}
