package com.example.user.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Document(collection = "users")
public class UserId {
    @Id
    private String id; // ObjectId generated by MongoDB
    private String username;
    private String password;
    private String nickname;
    private String avatar;//头像链接
    private int coins;
    private List<CoinRecord> coins_record;
    private List<String> followed = new ArrayList<>();
    private List<String> follower = new ArrayList<>();
    private String isFollowed;
    private List<String> blacklist;
    private List<String> questions_ask;
    private List<String> questions_asw;
    private List<String> questions_collect;
    private String ipaddress;

    public void setIsFollowed(String isFollowed) {
        this.isFollowed = isFollowed;
    }
    public String getIsFollowed() {
        return isFollowed;
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    public String getusername() {
        return username;
    }
    public void setusername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getCoins() {
        return coins;
    }

    public void setCoins(int coins) {
        this.coins = coins;
    }

    public List<CoinRecord> getCoins_record() {
        return coins_record;
    }

    public void setCoins_record(List<CoinRecord> coins_record) {
        this.coins_record = coins_record;
    }

    public List<String> getFollowed() {
        return followed;
    }

    public void setFollowed(List<String> followed) {
        this.followed = followed;
    }

    public List<String> getFollower() {
        return follower;
    }

    public void setFollower(List<String> follower) {
        this.follower = follower;
    }

    public List<String> getBlacklist() {
        return blacklist;
    }

    public void setBlacklist(List<String> blacklist) {
        this.blacklist = blacklist;
    }

    public List<String> getQuestions_ask() {
        return questions_ask;
    }

    public void setQuestions_ask(List<String> questions_ask) {
        this.questions_ask = questions_ask;
    }

    public List<String> getQuestions_asw() {
        return questions_asw;
    }

    public void setQuestions_asw(List<String> questions_asw) {
        this.questions_asw = questions_asw;
    }

    public List<String> getQuestions_collect() {
        return questions_collect;
    }

    public void setQuestions_collect(List<String> questions_collect) {
        this.questions_collect = questions_collect;
    }

    public String getIpaddress() {
        return ipaddress;
    }

    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    
}
